name: Blackjack
version: 2.1
main: com.vortex.blackjack.BlackjackPlugin
description: A physical blackjack table game for Minecraft
api-version: 1.21
depend: [Essentials]

commands:
  blackjack:
    description: Main command for the Blackjack plugin
    usage: |
      &8[&6Blackjack&8] &rAvailable Commands:
      &e/createtable &7- Create a new blackjack table
      &e/removetable &7- Remove the nearest table
      &e/join &7- Join the nearest table
      &e/leave &7- Leave your current table
      &e/start &7- Start a new game
      &e/hit &7- Take another card
      &e/stand &7- End your turn
      &e/doubledown &7- Double your bet and take exactly one more card
      &e/bet <amount> &7- Place or change your bet
      &e/stats [player] &7- View statistics (admins can check other players)
    aliases: [bj]
  createtable:
    description: Create a new blackjack table
    permission: blackjack.admin
  removetable:
    description: Remove the nearest blackjack table
    permission: blackjack.admin
  join:
    description: Join the nearest blackjack table
    permission: blackjack.play
  leave:
    description: Leave your current blackjack table
    permission: blackjack.play
  start:
    description: Start a new blackjack game
    permission: blackjack.play
  hit:
    description: Take another card in blackjack
    permission: blackjack.play
  stand:
    description: End your turn in blackjack
    permission: blackjack.play
  doubledown:
    description: Double your bet and take exactly one more card
    permission: blackjack.play
    aliases: [dd]
  bet:
    description: Place or change your bet in blackjack
    permission: blackjack.play
    usage: /bet <amount>
  stats:
    description: View your blackjack statistics or check another player's stats (admin only)
    permission: blackjack.play
    usage: /stats [player]
  bjversion:
    description: Check the plugin version and update status
    permission: blackjack.admin

permissions:
  blackjack.admin:
    description: Allows creation and removal of blackjack tables
    default: op
  blackjack.play:
    description: Allows playing blackjack
    default: true
  blackjack.stats.others:
    description: Allows checking other players' statistics
    default: op